services:
  backend:
    extends:
      file: docker-compose.back.yml
      service: backend

  db:
    extends:
      file: docker-compose.back.yml
      service: db

  redis:
    extends:
      file: docker-compose.back.yml
      service: redis

  frontend:
    extends:
      file: docker-compose.local.yml
      service: frontend

  celery:
    build: ./backend
    image: celery
    container_name: background
    command: celery -A src worker -l info
    networks: 
      - booking-network
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis

  flower:
    build: ./backend
    image: flower
    container_name: background_result
    command: celery -A src flower --port=5555
    ports:
      - 5556:5555
    networks:
      - booking-network
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      - celery


networks:
  booking-network:
    driver: bridge


volumes:
  db-booking-data:
    driver: local
