services:
  backend:
    extends:
      file: docker-compose.back.yml
      service: backend

  db:
    extends:
      file: docker-compose.back.yml
      service: db

  redis:
    extends:
      file: docker-compose.back.yml
      service: redis

  frontend:
    build: ./frontend
    image: react-app
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - booking-network
    depends_on:
      - backend


networks:
  booking-network:
    driver: bridge


volumes:
  db-booking-data:
    driver: local