services:
  backend:
    build: ./backend
    image: booking
    container_name: backend
    restart: unless-stopped
    networks:
      - booking-network
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    networks:
      - booking-network
    volumes:
      - db-booking-data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - booking-network


networks:
  booking-network:
    driver: bridge


volumes:
  db-booking-data:
    driver: local
