"""empty message

Revision ID: 2df1e12f9c07
Revises: 28635d92c6f7
Create Date: 2024-12-26 11:51:42.933743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df1e12f9c07'
down_revision: Union[str, None] = '28635d92c6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_offer_feedback', 'feedback', ['user_id', 'offer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_offer_feedback', 'feedback', type_='unique')
    # ### end Alembic commands ###
