"""empty message

Revision ID: 882e76f66546
Revises: d4e73d261c6a
Create Date: 2024-09-18 16:12:31.019115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882e76f66546'
down_revision: Union[str, None] = 'd4e73d261c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'check_rating',
        'feedback',
        sa.text('rating >= 1 AND rating <= 5')
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
