"""empty message

Revision ID: d4e73d261c6a
Revises: ca0b59db1622
Create Date: 2024-09-18 16:02:36.219350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e73d261c6a'
down_revision: Union[str, None] = 'ca0b59db1622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('feedback', sa.Column('rating', sa.SmallInteger(), nullable=False))
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'rating',
               existing_type=sa.SmallInteger(),
               type_=postgresql.ENUM('one', 'two', 'three', 'four', 'five', name='rate'),
               existing_nullable=False)
    # ### end Alembic commands ###
